[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd scraper-server && npm install"]

[phases.build]
cmds = ["cd scraper-server && npm run build || echo 'No build script'"]

[start]
cmd = "cd scraper-server && node server.js"
